SELECT MIN(CITY), LENGTH(CITY) FROM STATION
WHERE( 
    LENGTH(CITY) = (SELECT MAX(LENGTH(CITY)) FROM STATION) 
    OR LENGTH(CITY) = (SELECT MIN(LENGTH(CITY)) FROM STATION)
    )
GROUP BY LENGTH(CITY);
